version: "3.9"

services:

  # Database
  backstage_database:
    image: postgres:15.2-alpine
    container_name: backstage_database
    restart: always
    ports:
      - ${DATABASE_PORT}:5432
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    volumes:
      - pgdata:/data/postgres
    networks:
      - net

  # Application
  backstage_api:
    build: .
    container_name: backstage_api
    restart: always
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    volumes:
      - .:/app
    depends_on:
      - backstage_database
    links:
      - backstage_database
    networks:
      - net

networks:
  net:
    driver: bridge

volumes:
  pgdata:
    driver: local
